### ISSUE TITLE
newRidgeState is not exported from react-ridge-state with latest version

### ISSUE THREAD

**Issue by ludviglundgren** [web-ridge/react-ridge-state#26]
Hi,

With the latest release `4.2.4` I get this error during build and dev mode. Reverting back and pinning to `4.2.2` and it works again.

Log is from a github action docker build, but local log is the same. Checked over multiple systems as well.

```
 > [web-builder 6/6] RUN yarn build:
#23 0.440 yarn run v1.22.15
#23 0.488 $ react-scripts build
#23 2.448 Creating an optimized production build...
#23 39.99 Failed to compile.
#23 39.99 
#23 39.99 Attempted import error: 'newRidgeState' is not exported from 'react-ridge-state' (imported as 'newRidgeState').
#23 39.99 
#23 39.99 
#23 40.05 error Command failed with exit code 1.
#23 40.05 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
error: failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1
Error: buildx failed with: error: failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1
```

**Comment by RichardLindhout** [comment]
4.2.6 should be used, there was a wrong version indeed!

**Comment by ludviglundgren** [comment]
Thanks for getting back. Tried that version and it's still the same issue.

`Attempted import error: 'newRidgeState' is not exported from 'react-ridge-state' (imported as 'newRidgeState').`

Using it like the docs says, and as before on `4.2.2` with `import { newRidgeState } from "react-ridge-state";`

There must be something you're missing with how it's built now and the stuff you changed for the build. I don't know much about building modules so can't really help out with that.

**Comment by RichardLindhout** [comment]
Should work now

**Comment by RichardLindhout** [comment]
It added more bytes to bundle though but I think it's too early to use too much modern javascript in final bundle so I compile with tsc now instead of esbuild
